### ISSUE TITLE
Rowdy Racers Art and Animations

### ISSUE THREAD

**Issue by rossquentin** [HuskyGameDev/2022f-team2#3]

**Comment by CaptainCarried** [comment]
currently working on one of the racers. 
Name: Lightning Rod
Description: Races at a unremarkable speed, has a chance to get struck by lightning and speed up during race.
![Thunder Rod (1)](https://user-images.githubusercontent.com/112495496/192898547-cd4b1367-f55a-4db2-a4e1-989bfce1da34.png)
